### PR TITLE
minor changes, edits, deletions. See diff

### PR DESCRIPTION
**Pull request by andy5995**
Thought I'd dip my toe in the water, so to speak. Let me know if any changes need to made to this pull request.

### CODE REVIEW

**Comment by rawsonj** [comment]
Hi Andy,

I just have 2 bits of feedback.

1: Thanks for the SSL parts. My preference would be to implement the switch explicitly as "yes" or "no" rather than anything or "NO," but I don't see that as a blocker for merging. Only reason why is "explicit is better than implicit," and I think it's reasonable to throw an exception if a config setting isn't properly set.

2: You added a print(savefile) to an exception handler, and I was just curious why? Also, the more I look at that code the more it should be rewritten entirely... *sigh*

I wrote this when I was learning python and twisted, and cleaning up the bot and rewriting it has been perpetually on my todo list.

**Comment by andy5995** [comment]
Hi @rawsonj 
I should have deleted `print(savefile)`. I put that there earlier tonight because I couldn't figure out why the connection was failing (that error showed with save file not found). So I decided to print out the variable so I could see it.

Turns out the connection was failing because I couldn't connect with SSL. And as you know, the save file (scores.json) is created upon the first successful startup. So no problem with that.

I never coded python before today. I've been slowly learning C over 20 years though. ;) Best of luck to you.

**Comment by rawsonj** [comment]
No worries. I'll remove that, and make the switch more explicit.

And thanks! :)

**Comment by andy5995** [comment]
Ok, thanks for taking care of that. In the future, feel free to ask me to make changes before a final commit. :)

**Pull request merged**
