### PR TITLE
questions_48: removed "Useless trivia" from 2 lines

### PR DESCRIPTION
**Pull request by andy5995**
Nice catch on commit https://github.com/rawsonj/triviabot/commit/fa7bf7e08e175121e4b0c40ed12c83b628cf3797 @rawsonj 

Thought I'd take care of the other two. Cheers!

### CODE REVIEW

**Comment by rawsonj** [comment]
Sorry man, been busy.

I'll review soon.

**Comment by rawsonj** [comment]
Also, I forgot what network you had me connect to. My server had a power event and I forgot to save the config. What was it again?

**Comment by andy5995** [comment]
No worries about the delay.

Network? You mean for IRC? The info is in your README :)

I've been working on a new project, related to mental health. Started in 2014, I just joined a few weeks ago. The team would welcome more feedback and input from veterans. If you're interested in an invite to the development chatroom, let me know.

The project is pinned on my GitHub profile.

**Comment by rawsonj** [comment]
lol, ok, reviewed this finally.

Yep, agree.

**Pull request merged**
